server:
  port: 18050
spring:
  application:
    name: car
  datasource:
    username: admin
    password: admin
    url: jdbc:h2:mem:cardb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: "/h2-console"
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
springdoc:
  version: '1.0'
  swagger-ui:
    use-root-path: true